version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: bot_postgres
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASWOR_DB}
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
    driver: bridge
